### ISSUE TITLE
Clickable Tiles

### ISSUE THREAD

**Issue by ayush18verma** [developer-shivam/ChanelView#1]
How to make tilesContainer clickable to open new fragment ? Please help

**Comment by developer-shivam** [comment]
I have added setOnClickListener() on tiles and buttons too. Check code thoroughly!
Use switch case.

**Comment by ayush18verma** [comment]
I already used switch case and implement listeners but it didn't clicked. What to pass in the arguements of switch case?

**Comment by ayush18verma** [comment]
If i use activity then its working fine, but if i take fragment , after clicking on tiles. it doesn't worked. Please resolve it soon.

**Comment by developer-shivam** [comment]
Talk is cheap. Show me the code!

**Comment by ayush18verma** [comment]
http://pastebin.com/L9aYMhSJ

**Comment by developer-shivam** [comment]
I will try to update this repository as per your requirement by this weekend.

**Comment by ayush18verma** [comment]
Thank you. Will wait

**Comment by developer-shivam** [comment]
@ayush18verma Please check!

**Comment by ayush18verma** [comment]
Sorry to say! Its not working :(

**Comment by developer-shivam** [comment]
Download my code and run. Its working.

**Comment by ayush18verma** [comment]
Yeah your code is working, but same thing as i did, but its not clickable and goes to fragment view. :(

**Comment by developer-shivam** [comment]
Can't help you without seeing you code.

**Comment by ayush18verma** [comment]
http://pastebin.com/s28z2LFC
can you please check it out? Thank you

**Comment by ayush18verma** [comment]
@developer-shivam Did you looked out my code?

**Comment by developer-shivam** [comment]
Can you please connect with me over Facebook (https://m.facebook.com/developerShivam) or LinkedIn (https://in.linkedin.com/in/developershivam)

Thanks
